services:
    diffy:
        build: './docker/'
        volumes:
            - "./:/diffy-worker"
            - "../tmp:/tmp"
        command: tail -f /dev/null
        tty: true
        ports:
            - "9229:9229"
        env_file:
            -   .env
